config/routes.rb
SubwayStatus::Application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :alerts
  get '/dashboard' => 'welcome#dashboard'
  get '/ping' => 'welcome#ping'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
belongs_to :train
belongs_to :user
has_and_belongs_to_many :days
end

app/models/day.rb
class Day < ActiveRecord::Base
has_and_belongs_to_many :alerts

end

app/models/record.rb
class Record < ActiveRecord::Base

end

app/models/train.rb
class Train < ActiveRecord::Base
has_many :alerts

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :alerts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  def new
    @alert = Alert.new
  end

  def create
    @alert = Alert.new(alert_params)

    if user_signed_in?
      @alert.save
      redirect_to dashboard_path
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    @alert = Alert.find(params[:id])
  end

  def update
    @alert = Alert.find(params[:id])

    if @alert.update_attributes(alert_params)
      redirect_to dashboard_path
    end
  end

  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy
    redirect_to dashboard_path
  end

private

def alert_params
  params[:alert].permit(
    :name,
    :time_to_send,
    :train_id,
    :user_id,
    :recurring,
    {:day_ids => []}
  )
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/trains_controller.rb
class TrainController < ApplicationController

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to dashboard_path
      return
    end

    @alert = Alert.new
    @line123 = Train.find(1)
    @line456 = Train.find(2)
    @line7 = Train.find(3)
    @lineACE = Train.find(4)
    @lineBDFM = Train.find(5)
    @lineG = Train.find(6)
    @lineJZ = Train.find(7)
    @lineL = Train.find(8)
    @lineNQR = Train.find(9)
    @lineS = Train.find(10)
    @lineSIR = Train.find(11)
  end

  def ping
    render json: "Track"
  end

  def dashboard
    @alerts = Alert.where(user_id: current_user.id)

    @alert = Alert.new
    @line123 = Train.find(1)
    @line456 = Train.find(2)
    @line7 = Train.find(3)
    @lineACE = Train.find(4)
    @lineBDFM = Train.find(5)
    @lineG = Train.find(6)
    @lineJZ = Train.find(7)
    @lineL = Train.find(8)
    @lineNQR = Train.find(9)
    @lineS = Train.find(10)
    @lineSIR = Train.find(11)
  end

  private
  #This is all my privates below
  def alert_params
    params.require(:alert).permit(:time_to_send, :train_id, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/alerts/_form.html.erb
<div class="form-holder">

<%= form_for @alert, :html => {:class => "form-inline"} do |f| %>

<%= f.label :name, "Alert name?", {:class => "welcome-alert-form lato"} %>
<%= f.text_field :name, :placeholder => "Alert name", :type => "text" %>


&nbsp;

<%= f.label :time_to_send, "When?", {:class => "welcome-alert-form lato"} %>
<%= time_select 'alert', 'time_to_send', {:minute_step => 15, :ampm => true, :ignore_date => true} %>

&nbsp;

<%= f.label "Train?", {:class => "welcome-alert-form lato"} %>
<%= f.collection_select :train_id, Train.all, :id, :name, {}, {:class => "narrow"} %>

&nbsp;

<!-- <%= f.label "Recurring?", {:class => "welcome-alert-form lato"} %>
<%= f.select :recurring, [['Yes', true], ['No', false]], {}, :class => "alert_recurring" %> -->

<div class="days-form">
  <%= hidden_field_tag "alert[day_ids][]", nil %>
<%= f.label "Which days?", {:class => "welcome-alert-form lato"} %>
  <% Day.all.each do |day| %>
    <%= check_box_tag "alert[day_ids][]", day.id, @alert.day_ids.include?(day.id) %>
    <%= day.name %>
  <% end %>
</div>

<% if user_signed_in? %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<% end %>

&nbsp;
<%= f.submit "Submit", {:class => "btn btn-primary"} %>
<% end %>
</div>

app/views/alerts/edit.html.erb
<%= render 'form' %>

app/views/alerts/edit.js.erb
$('#<%= @alert.id %>').hide();
$('#table').after('<%= j render("/alerts/form") %>');

app/views/alerts/new.html.erb
<%= render 'form' %>

app/views/alerts/new.js.erb
$('#add-alert').hide();
$('#table').after('<%= j render("/alerts/form") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Track</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Quattrocento' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>

<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43648984-2', 'trackmta.herokuapp.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/welcome/_aboutmodal.html.erb
  <div class="modal fade" id="About-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="quattro">ABOUT</h4>
        </div>
        <div class="modal-body lato">
          Track pulls service status data from the MTA's website every 10 minutes. The data is then matched against a database of users' alerts. When a user's requested alert time matches the current time, the server will send an email to the user's address containing a short summary of the requested subway line's service status. <br><br>

          Example:<br>
          Fred typically takes the L train into Manhattan each morning at approximately 8:45. He creates a Track account and adds a new alert for the L train at 8:15 AM. Just like that, Fred can know -- before he even leaves his apartment -- if the L train will have any service issues that morning. <br><br>

          <img src="http://s3.amazonaws.com/TrackAppImage/mtalogo.jpg" width="180px"/>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/welcome/_alertslogos.html.erb
<% case @alert.train.name %>
<% when "123" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/1.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/2.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/3.png" /></div>

<% when "456" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/4.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/5.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/6.png" /></div>

<% when "ACE" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/a.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/c.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/e.png" /></div>

<% when "7" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/7.png" /></div>

<% when "BDFM" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/b.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/d.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/f.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/m.png" /></div>

<% when "G" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/g.png" /></div>

<% when "JZ" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/j.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/z.png" /></div>

<% when "L" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/l.png" /></div>

<% when "NQR" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/n.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/q.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/r.png" /></div>

<% when "S" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/s.png" /></div>

<% when "SIR" %>
<div class="btn btn-default" disabled="disabled"><img src=" http://s3.amazonaws.com/TrackAppImage/sir.png" /></div>
<% end %>


<!-- case grade
when "A"
  puts 'Well done!'
when "B"
  puts 'Try harder!'
when "C"
  puts 'You need help!!!'
else
  puts "You just making it up!"
end -->

app/views/welcome/_alertstable.html.erb
<table id="table">

  <thead>
    <tr>
      <th class="alert-table-columns">Alert Name</th>
      <th class="alert-table-columns">Time</th>
      <th class="alert-table-columns">Train</th>
      <!-- <th class="alert-table-columns">Recurring?</th> -->
      <th class="alert-table-columns">Days</th>
      <th class="alert-table-columns"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
    <% @alert = alert %>
    <tr>
      <td><%= @alert.name %></td>
      <td><%= @alert.time_to_send.strftime("%I:%M %p") %></td>
      <td><%= render 'alertslogos' %></td>
<!--       <td>
        <% if @alert.recurring == true %>
        <p>Yes</p>
        <% elsif @alert.recurring == false %>
        <p>No</p>
        <% end %>
      </td> -->

      <td>
        <% @alert.days.each do |day| %>

        <div class="btn btn-default" disabled="disabled"><%= day.nickname %></div>
        <% end %>
      </td>

      <td>
        <%= link_to "<i class=\"icon-edit icon-white\"></i> Edit".html_safe, edit_alert_path(:id => alert.id), {:class => "btn btn-default", id: alert.id, remote: true} %>
        <%= link_to "<i class=\"icon-remove icon-white\"></i> Delete".html_safe, alert, {method: :delete, :class => "btn btn-danger"} %>
      </td>
    </tr>
    <% end %>

  </tbody>

</table>

app/views/welcome/_createaccountmodal.html.erb
  <div class="modal fade" id="create-account-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none">
    <div class="modal-dialog narrowmodal">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="quattro">CREATE ACCOUNT</h4>
        </div>
        <div class="modal-body">
          <%= render '/devise/registrations/form' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/welcome/_edituser.html.erb
  <div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none">
    <div class="modal-dialog narrowmodal">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="quattro">EDIT USER</h4>
        </div>
        <div class="modal-body">
          <%= render '/devise/registrations/editform' %>
          <%= button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => "btn btn-danger" %><br>
          <div class="footnote-text lato">
          * Leave blank if you don't want to change it<br>
          ^ We need your current password to confirm your changes)
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/welcome/_loginmodal.html.erb
  <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none">
    <div class="modal-dialog narrowmodal">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="quattro">LOG IN</h4>
        </div>
        <div class="modal-body">
          <%= render '/devise/sessions/form' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/welcome/_navbar.html.erb
<nav>
  <ul class="navbar quattro">
    <% if user_signed_in? %>
    <li><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></li>
    <% end %>

    <li><a href="mailto:track.automailer+feedback@gmail.com?Subject=[TRACK]%20Feedback">CONTACT</a></li>
    <li><a data-toggle="modal" href="#About-modal">ABOUT</a></li>
    <li><a data-toggle="modal" href="#status-modal">STATUS</a></li>
    <% if user_signed_in? %>
    <li><a href="/dashboard"><%= current_user.email %></a></li>
    <% else %>
    <li><a data-toggle="modal" href="#login-modal">LOG IN</a></li>
    <% end %>
  </ul>
</nav>

app/views/welcome/_statusmodal.html.erb
  <div class="modal fade" id="status-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none">
    <div class="modal-dialog statusmodal">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="quattro">CURRENT SUBWAY STATUS</h4>
        </div>
        <div class="modal-body lato">
         <%= render 'statustable' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/welcome/_statustable.html.erb
<table>
    <thead>
      <tr>
        <th class="status_td">Train</th>
        <th class="status_td">Status</th>
        <th class="status_td"></th>
      </tr>
    </thead>

    <tbody>
      <!-- 123 TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/1.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/2.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/3.png" /></td>

        <td class="status_td"><%= @line123.status %></td>
        <% if @line123.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="line123" data-content="<%= @line123.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- 456 TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/4.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/5.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/6.png" /></td>

        <td class="status_td"><%= @line456.status %></td>
        <% if @line456.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="line456" data-content="<%= @line456.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- 7 TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/7.png" /></td>

        <td class="status_td"><%= @line7.status %></td>
        <% if @line7.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="line7" data-content="<%= @line7.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- ACE TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/a.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/c.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/e.png" /></td>

        <td class="status_td"><%= @lineACE.status %></td>
        <% if @lineACE.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineACE" data-content="<%= @lineACE.text %>">Info</div><br/>
          <% end %>
        </td>

      </tr>

      <!-- BDFM -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/b.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/d.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/f.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/m.png" /></td>

        <td class="status_td"><%= @lineBDFM.status %></td>
        <% if @lineBDFM.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineBDFM" data-content="<%= @lineBDFM.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- G TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/g.png" /></td>

        <td class="status_td"><%= @lineG.status %></td>
        <% if @lineG.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineG" data-content="<%= @lineG.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- JZ TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/j.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/z.png" /></td>

        <td class="status_td"><%= @lineJZ.status %></td>
        <% if @lineJZ.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineJZ" data-content="<%= @lineJZ.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- L TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/l.png" /></td>

        <td class="status_td"><%= @lineL.status %></td>
        <% if @lineL.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineL" data-content="<%= @lineL.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- NQR TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/n.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/q.png" /><img src=" http://s3.amazonaws.com/TrackAppImage/r.png" /></td>

        <td class="status_td"><%= @lineNQR.status %></td>
        <% if @lineNQR.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineNQR" data-content="<%= @lineNQR.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- S TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/s.png" /></td>

        <td class="status_td"><%= @lineS.status %></td>
         <% if @lineS.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineS" data-content="<%= @lineS.text %>">Info</div><br/>
          <% end %>
      </tr>

      <!-- SIR TRAIN -->
      <tr>
        <td class="status_td"><img src=" http://s3.amazonaws.com/TrackAppImage/sir.png" /></td>

        <td class="status_td"><%= @lineSIR.status %></td>
        <% if @lineSIR.status != "GOOD SERVICE" %>
        <td class="status_td"><div class="btn btn-default line-info" href="#" data-toggle="popover" id="lineSIR" data-content="<%= @lineSIR.text %>">Info</div><br/>
          <% end %>
      </tr>
    </tbody>
  </table>

app/views/welcome/dashboard.html.erb
<div class="title quattro">TRACK</div>
<%= render '/welcome/navbar' %>

<div class="dashboard-text quattro">Dashboard</div><br>
<div class="border-container"></div>


<div class="dashboard-left-container">
  <div class="dashboard-left dashboard-top lato">
    User Alerts<br><br>
    <%= link_to "<i class=\"icon-plus icon-white\"></i> Add New Alert".html_safe, new_alert_path, {:class => "btn btn-primary", :id => "add-alert", remote: true} %>
  </div>

  <div class="dashboard-left dashboard-bottom lato">User Settings</div>
</div>

<div class="dashboard-right-container">
  <div class="dashboard-right dashboard-top">
    <%= render 'alertstable' %>
  </div>

  <div class="dashboard-right dashboard-bottom">
    <button data-toggle="modal" href="#edit-user-modal" class="btn">Edit Account Settings</button>
  </div>
</div>

  <!-- Button trigger modal -->




<!-- Modal -->
<%= render 'aboutmodal' %>
<%= render 'edituser' %>
<%= render 'statusmodal' %>

app/views/welcome/index.html.erb
  <div class="title quattro">TRACK</div>
  <%= render '/welcome/navbar' %>

<div class="container">
  <div class="welcome-text quattro">Daily MTA service status updates, personalized</div><br>

  <% if user_signed_in? %>
    <div class="welcome-alert-form lato"><%= link_to "Go to Dashboard", dashboard_path, {:class => "btn btn-primary"} %></div><br>
    <div class="welcome-alert-form lato"><%= link_to "View Current Subway Status", dashboard_path, {:class => "btn btn-primary"} %></div>
  <% else %>

    <div class="welcome-alert-form lato"><button data-toggle="modal" href="#login-modal" class="btn btn-primary">Log In</button></div><br>
    <div class="welcome-alert-form lato"><button data-toggle="modal" href="#create-account-modal" class="btn btn-primary">Create Account</button></div>
  <% end %>
</div>

  <!-- Modals -->
<%= render 'aboutmodal' %>
<%= render 'loginmodal' %>
<%= render 'createaccountmodal' %>
<%= render 'statusmodal' %>